# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f91ec9288bbdeab3afed8bcc2fb25d2829e26633e52c5ed19369aa8991af5cb7840344f56fb80659849bbe58c17cbf82adf0ec835df5be3dca1044217e025d73

test:
  secret_key_base: db7c5a37bb4b6198f86de597d81bf7cb7877594bf39216c74ce67eb30f67c44db499dcebb45a4d9711e3e62e49eb668a612fc171b0801015144adc316ee6f6ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
